CREATE DATABASE IF NOT EXISTS NHKdb 
CHARACTER SET = utf8mb4 
COLLATE = utf8mb4_unicode_ci;

USE NHKdb;

CREATE TABLE IF NOT EXISTS kanji_count (
	id INT AUTO_INCREMENT PRIMARY KEY,
	kanji VARCHAR(64) NOT NULL UNIQUE,
	count INT
);

CREATE TABLE IF NOT EXISTS metadata (
	id INT AUTO_INCREMENT PRIMARY KEY,
	last_processed_id VARCHAR(64) NOT NULL,
	processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS processed_hashes (
    text_hash VARCHAR(64) PRIMARY KEY
);