FROM apache/airflow:2.9.0-python3.10

# Install dependencies
USER root
RUN apt-get update && apt-get install -y \
    wget gnupg curl unzip \
    libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 \
    libxcomposite1 libxdamage1 libxrandr2 libgbm1 libasound2 \
    libxshmfence1 libxss1 libxtst6 xdg-utils

# Install Playwright
USER airflow
RUN pip install playwright && playwright install --with-deps
