FROM python:3.12-slim

WORKDIR /opt

COPY flask.requirements.txt flask.requirements.txt
RUN pip install --no-cache-dir -r flask.requirements.txt

ENV MONGO_HOST=nhk-mongo

EXPOSE 5000

CMD ["python", "show_articles.py"]
