# add -d to docker-compose up to run detatched
# docker-compose up -d
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# Basic Airflow cluster configuration for CeleryExecutor with Redis and PostgreSQL.
#
# WARNING: This configuration is for local development. Do not use it in a production deployment.
#
# This configuration supports basic configuration using environment variables or an .env file
# The following variables are supported:
#
# AIRFLOW_IMAGE_NAME           - Docker image name used to run Airflow.
#                                Default: apache/airflow:master-python3.8
# AIRFLOW_UID                  - User ID in Airflow containers
#                                Default: 50000
# AIRFLOW_GID                  - Group ID in Airflow containers
#                                Default: 50000
#
# Those configurations are useful mostly in case of standalone testing/running Airflow in test/try-out mode
#
# _AIRFLOW_WWW_USER_USERNAME   - Username for the administrator account (if requested).
#                                Default: airflow
# _AIRFLOW_WWW_USER_PASSWORD   - Password for the administrator account (if requested).
#                                Default: airflow
# _PIP_ADDITIONAL_REQUIREMENTS - Additional PIP requirements to add when starting all containers.
#                                Default: ''

x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  image: nhk-airflow-custom:latest
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: mysql+mysqlconnector://root:MyNewPass@mysql:3306/NHKdb
    AIRFLOW__CELERY__RESULT_BACKEND: db+mysql+mysqlconnector://root:MyNewPass@mysql:3306/NHKdb
    AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
    MONGO_HOST: mongodb
    MYSQL_HOST: nhk-mysql
  volumes:
    - ./airflow:/opt/airflow
  depends_on:
    redis:
      condition: service_healthy
    mysql:
      condition: service_healthy

services:
  mysql:
    image: mysql:8.0
    container_name: nhk-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MyNewPass
      MYSQL_DATABASE: NHKdb
    volumes:
      - ./mysql-init/nhkDB.sql:/docker-entrypoint-initdb.d/nhkDB.sql
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: nhk-redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50

  airflow-webserver:
    <<: *airflow-common
    container_name: nhk-airflow-webserver
    command: webserver
    ports:
      - 8080:8080
    environment:
      <<: *airflow-common-env
      PROJECT_PATH: /opt/airflow
      MONGO_HOST: nhk-mongo
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    container_name: nhk-airflow-scheduler
    command: scheduler
    environment:
      <<: *airflow-common-env
      PROJECT_PATH: /opt/airflow
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-worker:
    <<: *airflow-common
    container_name: nhk-airflow-worker
    command: celery worker
    environment:
      <<: *airflow-common-env
      PROJECT_PATH: /opt/airflow
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-init:
    <<: *airflow-common
    container_name: nhk-airflow-init
    command: >
      bash -c "
      airflow db upgrade &&
      airflow users create --username airflow --password airflow --firstname Air --lastname Flow --role Admin --email airflow@example.com
      "
    environment:
      <<: *airflow-common-env

  mongodb:
    image: mongo:6.0
    container_name: nhk-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: nhk-mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: nhk-mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
    ports:
      - "8082:8081"
    depends_on:
      - mongodb
        
  flask-app:
    container_name: nhk-flask-app
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    environment:
      - MONGO_USER=mongo
      - MONGO_PASS=mongo
      - MONGO_HOST=nhk-mongo
    depends_on:
      - mongodb
      
  playwright:
    container_name: nhk-playwright
    build:
      context: .
      dockerfile: Dockerfile.playwright
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "5010:5010"
    shm_size: 1g
    restart: unless-stopped
    command: python /opt/airflow/playwright_api.py

        
volumes:
  mysql-data:
  mongo-data:

